version: '3.9'
services:
  whatsapp-api:
    image: diogenesssantos/whatsapp-api
    restart: always
    build: .
    working_dir: /rest-with-spring-boot-and-kotlin-whatsapp-api
    ports:
      - 80:8080